# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from kenjo_python_sdk.paths.compensation_contracts.get import GetContractsRaw
from kenjo_python_sdk.paths.compensation_salaries.get import GetSalariesListRaw
from kenjo_python_sdk.paths.compensation_additional_payment_types.get import ListAdditionalPaymentTypesRaw
from kenjo_python_sdk.paths.compensation_additional_payments.get import ListAdditionalPaymentsRaw
from kenjo_python_sdk.paths.compensation_contract_types.get import ListContractTypesRaw


class CompensationApiRaw(
    GetContractsRaw,
    GetSalariesListRaw,
    ListAdditionalPaymentTypesRaw,
    ListAdditionalPaymentsRaw,
    ListContractTypesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
