# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from kenjo_python_sdk.paths.employees_employee_id_activate.put import ActivateEmployee
from kenjo_python_sdk.paths.employees.post import CreateInactiveEmployee
from kenjo_python_sdk.paths.employees_employee_id_deactivate.put import DeactivateEmployeeById
from kenjo_python_sdk.paths.employees_accounts.get import GetAccounts
from kenjo_python_sdk.paths.employees_employee_id.get import GetEmployeeInformation
from kenjo_python_sdk.paths.employees.get import GetList
from kenjo_python_sdk.paths.employees_work_schedules.get import GetWorkSchedules
from kenjo_python_sdk.paths.employees_addresses.get import ListAddresses
from kenjo_python_sdk.paths.employees_financials.get import ListFinancials
from kenjo_python_sdk.paths.employees_homes.get import ListHomes
from kenjo_python_sdk.paths.employees_personals.get import ListPersonals
from kenjo_python_sdk.paths.employees_works.get import ListWorks
from kenjo_python_sdk.paths.employees_employee_id_addresses.put import UpdateAddress
from kenjo_python_sdk.paths.employees_employee_id_accounts.put import UpdateEmployeeAccounts
from kenjo_python_sdk.paths.employees_employee_id_financials.put import UpdateFinancials
from kenjo_python_sdk.paths.employees_employee_id_homes.put import UpdateHome
from kenjo_python_sdk.paths.employees_employee_id_personals.put import UpdatePersonals
from kenjo_python_sdk.paths.employees_employee_id_work_schedules.put import UpdateWorkSchedule
from kenjo_python_sdk.paths.employees_employee_id_works.put import UpdateWorks
from kenjo_python_sdk.apis.tags.employees_api_raw import EmployeesApiRaw


class EmployeesApi(
    ActivateEmployee,
    CreateInactiveEmployee,
    DeactivateEmployeeById,
    GetAccounts,
    GetEmployeeInformation,
    GetList,
    GetWorkSchedules,
    ListAddresses,
    ListFinancials,
    ListHomes,
    ListPersonals,
    ListWorks,
    UpdateAddress,
    UpdateEmployeeAccounts,
    UpdateFinancials,
    UpdateHome,
    UpdatePersonals,
    UpdateWorkSchedule,
    UpdateWorks,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeesApiRaw(api_client)
