# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from kenjo_python_sdk.paths.offices.post import CreateNewOffice
from kenjo_python_sdk.paths.offices_id.get import GetById
from kenjo_python_sdk.paths.offices.get import GetList
from kenjo_python_sdk.paths.offices_id.delete import RemoveById
from kenjo_python_sdk.paths.offices_id.put import UpdateOfficeAttributes
from kenjo_python_sdk.apis.tags.offices_api_raw import OfficesApiRaw


class OfficesApi(
    CreateNewOffice,
    GetById,
    GetList,
    RemoveById,
    UpdateOfficeAttributes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OfficesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OfficesApiRaw(api_client)
