# coding: utf-8

# flake8: noqa

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from kenjo_python_sdk.api_client import ApiClient

# import Configuration
from kenjo_python_sdk.configuration import Configuration

# import exceptions
from kenjo_python_sdk.exceptions import OpenApiException
from kenjo_python_sdk.exceptions import ApiAttributeError
from kenjo_python_sdk.exceptions import ApiTypeError
from kenjo_python_sdk.exceptions import ApiValueError
from kenjo_python_sdk.exceptions import ApiKeyError
from kenjo_python_sdk.exceptions import ApiException

from kenjo_python_sdk.client import Kenjo
