# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from kenjo_python_sdk.pydantic.attendance_get_expected_time_by_user_response_data_item_days import AttendanceGetExpectedTimeByUserResponseDataItemDays

class AttendanceGetExpectedTimeByUserResponseDataItem(BaseModel):
    # The Kenjo _id of the returned user.
    user_id: typing.Optional[str] = Field(None, alias='userId')

    days: typing.Optional[AttendanceGetExpectedTimeByUserResponseDataItemDays] = Field(None, alias='days')

    # The total number of expected hours for an user in a given date range.
    total_expected_hours: typing.Optional[typing.Union[int, float]] = Field(None, alias='totalExpectedHours')

    # The total number of expected minutes for an user in a given date range.
    total_expected_minutes: typing.Optional[typing.Union[int, float]] = Field(None, alias='totalExpectedMinutes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
