# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from kenjo_python_sdk.pydantic.attendance_create_entry_response_breaks import AttendanceCreateEntryResponseBreaks

class AttendanceCreateEntryResponse(BaseModel):
    # The Kenjo _id of the new attendance entry.
    _id: typing.Optional[str] = Field(None, alias='_id')

    # The id of the employee assigned to the requested attendance entry.
    user_id: typing.Optional[str] = Field(None, alias='userId')

    # The email of the employee assigned to the requested attendance entry.
    email: typing.Optional[str] = Field(None, alias='email')

    # The external Id of the employee assigned to the requested attendance entry.
    external_id: typing.Optional[str] = Field(None, alias='externalId')

    # The start date time of the created attendance entry
    start_time: typing.Optional[str] = Field(None, alias='startTime')

    # The end date time of the created attendance entry.
    end_time: typing.Optional[str] = Field(None, alias='endTime')

    breaks: typing.Optional[AttendanceCreateEntryResponseBreaks] = Field(None, alias='breaks')

    # DEPRECATED field, use the 'breaks' field to specify the breaktime. The time in minutes to indicate a break of time. It cannot be greater than the total of minutes reported for the attendance entry.
    break_time: typing.Optional[typing.Union[int, float]] = Field(None, alias='breakTime')

    # Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
    comment: typing.Optional[str] = Field(None, alias='comment')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
