# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CompensationGetSalariesListResponseDataItem(BaseModel):
    # The Kenjo _id of the returned salary.
    _id: typing.Optional[str] = Field(None, alias='_id')

    # The employee id associated to the salary.
    _user_id: typing.Optional[str] = Field(None, alias='_userId')

    # The company id associated to the salary.
    _company_id: typing.Optional[str] = Field(None, alias='_companyId')

    # The start date (effective date) of the salary in format YYYY-MM-DDThh:mm:ss.
    start_date: typing.Optional[str] = Field(None, alias='startDate')

    # The end date of the salary in format YYYY-MM-DDThh:mm:ss.
    end_date: typing.Optional[str] = Field(None, alias='endDate')

    # The the amount of money associated to the salary.
    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    # The salary payment period.
    payment_period: typing.Optional[str] = Field(None, alias='paymentPeriod')

    # This currency in ISO 4217.
    currency: typing.Optional[typing.Union[int, float]] = Field(None, alias='currency')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
