# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class EmployeesCreateInactiveEmployeeRequestWorkSchedule(BaseModel):
    # Allow to indicate if mondays are working days for the employee.
    monday_working_day: typing.Optional[bool] = Field(None, alias='mondayWorkingDay')

    # Allow to indicate if tuesdays are working days for the employee.
    tuesday_working_day: typing.Optional[bool] = Field(None, alias='tuesdayWorkingDay')

    # Allow to indicate if wednesdays are working days for the employee.
    wednesday_working_day: typing.Optional[bool] = Field(None, alias='wednesdayWorkingDay')

    # Allow to indicate if thursdays are working days for the employee.
    thursday_working_day: typing.Optional[bool] = Field(None, alias='thursdayWorkingDay')

    # Allow to indicate if fridays are working days for the employee.
    friday_working_day: typing.Optional[bool] = Field(None, alias='fridayWorkingDay')

    # Allow to indicate if saturdays are working days for the employee.
    saturday_working_day: typing.Optional[bool] = Field(None, alias='saturdayWorkingDay')

    # Allow to indicate if sundays are working days for the employee.
    sunday_working_day: typing.Optional[bool] = Field(None, alias='sundayWorkingDay')

    # Allow to activate or deactivate the attendance tracking for the employee.
    track_attendance: typing.Optional[bool] = Field(None, alias='trackAttendance')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
