# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class OfficesCreateNewOfficeResponse(BaseModel):
    # The Kenjo id of the new office.
    _id: typing.Optional[str] = Field(None, alias='_id')

    # The new name of the office to create.
    name: typing.Optional[str] = Field(None, alias='name')

    # The company id of the office to create.
    company_id: typing.Optional[str] = Field(None, alias='companyId')

    # The calendar id of the office to create.
    calendar_id: typing.Optional[str] = Field(None, alias='calendarId')

    # The country of the office to create.
    country: typing.Optional[str] = Field(None, alias='country')

    # The postalcode of the office to create.
    postal_code: typing.Optional[str] = Field(None, alias='postalCode')

    # The city of the office to create.
    city: typing.Optional[str] = Field(None, alias='city')

    # The street of the office to create.
    street: typing.Optional[str] = Field(None, alias='street')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
