# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from kenjo_python_sdk import schemas  # noqa: F401


class EmployeesCreateInactiveEmployeeResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def account() -> typing.Type['EmployeesCreateInactiveEmployeeResponseAccount']:
                return EmployeesCreateInactiveEmployeeResponseAccount
        
            @staticmethod
            def personal() -> typing.Type['EmployeesCreateInactiveEmployeeResponsePersonal']:
                return EmployeesCreateInactiveEmployeeResponsePersonal
        
            @staticmethod
            def work() -> typing.Type['EmployeesCreateInactiveEmployeeResponseWork']:
                return EmployeesCreateInactiveEmployeeResponseWork
        
            @staticmethod
            def workSchedule() -> typing.Type['EmployeesCreateInactiveEmployeeResponseWorkSchedule']:
                return EmployeesCreateInactiveEmployeeResponseWorkSchedule
        
            @staticmethod
            def address() -> typing.Type['EmployeesCreateInactiveEmployeeResponseAddress']:
                return EmployeesCreateInactiveEmployeeResponseAddress
        
            @staticmethod
            def financial() -> typing.Type['EmployeesCreateInactiveEmployeeResponseFinancial']:
                return EmployeesCreateInactiveEmployeeResponseFinancial
        
            @staticmethod
            def home() -> typing.Type['EmployeesCreateInactiveEmployeeResponseHome']:
                return EmployeesCreateInactiveEmployeeResponseHome
            __annotations__ = {
                "account": account,
                "personal": personal,
                "work": work,
                "workSchedule": workSchedule,
                "address": address,
                "financial": financial,
                "home": home,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["account"]) -> 'EmployeesCreateInactiveEmployeeResponseAccount': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal"]) -> 'EmployeesCreateInactiveEmployeeResponsePersonal': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["work"]) -> 'EmployeesCreateInactiveEmployeeResponseWork': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workSchedule"]) -> 'EmployeesCreateInactiveEmployeeResponseWorkSchedule': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address"]) -> 'EmployeesCreateInactiveEmployeeResponseAddress': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["financial"]) -> 'EmployeesCreateInactiveEmployeeResponseFinancial': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["home"]) -> 'EmployeesCreateInactiveEmployeeResponseHome': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["account", "personal", "work", "workSchedule", "address", "financial", "home", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["account"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseAccount', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponsePersonal', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["work"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseWork', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workSchedule"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseWorkSchedule', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseAddress', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["financial"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseFinancial', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["home"]) -> typing.Union['EmployeesCreateInactiveEmployeeResponseHome', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["account", "personal", "work", "workSchedule", "address", "financial", "home", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        account: typing.Union['EmployeesCreateInactiveEmployeeResponseAccount', schemas.Unset] = schemas.unset,
        personal: typing.Union['EmployeesCreateInactiveEmployeeResponsePersonal', schemas.Unset] = schemas.unset,
        work: typing.Union['EmployeesCreateInactiveEmployeeResponseWork', schemas.Unset] = schemas.unset,
        workSchedule: typing.Union['EmployeesCreateInactiveEmployeeResponseWorkSchedule', schemas.Unset] = schemas.unset,
        address: typing.Union['EmployeesCreateInactiveEmployeeResponseAddress', schemas.Unset] = schemas.unset,
        financial: typing.Union['EmployeesCreateInactiveEmployeeResponseFinancial', schemas.Unset] = schemas.unset,
        home: typing.Union['EmployeesCreateInactiveEmployeeResponseHome', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmployeesCreateInactiveEmployeeResponse':
        return super().__new__(
            cls,
            *args,
            account=account,
            personal=personal,
            work=work,
            workSchedule=workSchedule,
            address=address,
            financial=financial,
            home=home,
            _configuration=_configuration,
            **kwargs,
        )

from kenjo_python_sdk.model.employees_create_inactive_employee_response_account import EmployeesCreateInactiveEmployeeResponseAccount
from kenjo_python_sdk.model.employees_create_inactive_employee_response_address import EmployeesCreateInactiveEmployeeResponseAddress
from kenjo_python_sdk.model.employees_create_inactive_employee_response_financial import EmployeesCreateInactiveEmployeeResponseFinancial
from kenjo_python_sdk.model.employees_create_inactive_employee_response_home import EmployeesCreateInactiveEmployeeResponseHome
from kenjo_python_sdk.model.employees_create_inactive_employee_response_personal import EmployeesCreateInactiveEmployeeResponsePersonal
from kenjo_python_sdk.model.employees_create_inactive_employee_response_work import EmployeesCreateInactiveEmployeeResponseWork
from kenjo_python_sdk.model.employees_create_inactive_employee_response_work_schedule import EmployeesCreateInactiveEmployeeResponseWorkSchedule
