# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from kenjo_python_sdk.type.attendance_get_by_id_response_breaks import AttendanceGetByIdResponseBreaks

class RequiredAttendanceGetByIdResponse(TypedDict):
    pass

class OptionalAttendanceGetByIdResponse(TypedDict, total=False):
    # The _id of the requested attendance entry.
    _id: str

    # The id of the employee associated to the requested attendance entry.
    userId: str

    # The email of the employee associated to the requested attendance entry.
    email: str

    # The external Id of the employee associated to the requested attendance entry.
    externalId: str

    # The start date time of the requested attendance entry.
    startTime: str

    # The end date time of the requested attendance entry.
    endTime: str

    breaks: AttendanceGetByIdResponseBreaks

    # Number of minutes of break time. If there is no 'breaktime' this field will not be in the response. This value is the sum of the total time of breaks.
    breakTime: typing.Union[int, float]

    # The Kenjo _id of the attendance category.
    attendanceCategoryId: str

    # The Kenjo _id of the attendance sub category.
    attendanceSubCategoryId: str

    # Optional text to describe an attendance record (pair of startTime and endTime). The maximum number of characters is 150.
    comment: str

class AttendanceGetByIdResponse(RequiredAttendanceGetByIdResponse, OptionalAttendanceGetByIdResponse):
    pass
