# coding: utf-8

"""
    Kenjo API

    Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeesCreateInactiveEmployeeRequestPersonal(TypedDict):
    # The name of the Kenjo employee. This field is required.
    firstName: str

    # The surname of the Kenjo employee. This field is required.
    lastName: str

class OptionalEmployeesCreateInactiveEmployeeRequestPersonal(TypedDict, total=False):
    # The complete name of the Kenjo employee.
    displayName: str

    # The employee gender. Only is valid one of the following values 'Male' (male), 'Female' (female) or 'Other' (other).
    gender: str

    # The employee birth date. Format YYYY-MM-DDThh:mm:ss.000Z.
    birthdate: str

class EmployeesCreateInactiveEmployeeRequestPersonal(RequiredEmployeesCreateInactiveEmployeeRequestPersonal, OptionalEmployeesCreateInactiveEmployeeRequestPersonal):
    pass
